/**
 * Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity;

// Generated Aug 19, 2013 3:24:55 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssignmentId generated by hbm2java
 */
@Embeddable
public class AssignmentId implements java.io.Serializable {

	private long unitId;
	private long operationalPeriodId;

	public AssignmentId() {
	}

	public AssignmentId(long unitId, long operationalPeriodId) {
		this.unitId = unitId;
		this.operationalPeriodId = operationalPeriodId;
	}

	@Column(name = "unit_id", nullable = false)
	public long getUnitId() {
		return this.unitId;
	}

	public void setUnitId(long unitId) {
		this.unitId = unitId;
	}

	@Column(name = "operational_period_id", nullable = false)
	public long getOperationalPeriodId() {
		return this.operationalPeriodId;
	}

	public void setOperationalPeriodId(long operationalPeriodId) {
		this.operationalPeriodId = operationalPeriodId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssignmentId))
			return false;
		AssignmentId castOther = (AssignmentId) other;

		return (this.getUnitId() == castOther.getUnitId())
				&& (this.getOperationalPeriodId() == castOther
						.getOperationalPeriodId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUnitId();
		result = 37 * result + (int) this.getOperationalPeriodId();
		return result;
	}

}
