/**
 * Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity;

// Generated Sep 30, 2011 1:24:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Formtype generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "formtype")
public class FormType implements SADisplayPersistedEntity {

	private int formtypeid;
	private String formtypename;
	//private Set<Form> forms = new HashSet<Form>(0);

	public FormType() {
	}

	public FormType(int formtypeid, String formtypename) {
		this.formtypeid = formtypeid;
		this.formtypename = formtypename;
	}

	/*public FormType(int formtypeid, String formtypename, Set<Form> forms) {
		this.formtypeid = formtypeid;
		this.formtypename = formtypename;
		this.forms = forms;
	}*/

	@Id
	@Column(name = "formtypeid", unique = true, nullable = false)
	public int getFormTypeId() {
		return this.formtypeid;
	}

	public void setFormTypeId(int formtypeid) {
		this.formtypeid = formtypeid;
	}

	@Column(name = "formtypename", nullable = false, length = 60)
	public String getFormTypeName() {
		return this.formtypename;
	}

	public void setFormTypeName(String formtypename) {
		this.formtypename = formtypename;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "formtype")
	public Set<Form> getForms() {
		return this.forms;
	}

	public void setForms(Set<Form> forms) {
		this.forms = forms;
	}*/

}
