/**
 * Copyright (c) 2008-2016, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity;

// Generated Sep 30, 2011 1:24:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Log generated by hbm2java
 */
@Entity
@Proxy(lazy=true)
@Table(name = "log_workspace")
public class LogWorkspace extends SADisplayMessageEntity implements SADisplayPersistedEntity {

	private int logworkspaceid;
	private int logid;
	private int workspaceid;
	private Log log;

	public LogWorkspace() {
	}

	public LogWorkspace(int logid, int workspaceid) {
		this.logid = logid;
		this.workspaceid = workspaceid;
	}
	
	@Id @GeneratedValue
	@Column(name = "log_workspace_id", unique = true, nullable = false)
	public int getLogworkspaceid() {
		return this.logworkspaceid;
	}

	public void setLogworkspaceid(int logworkspaceid) {
		this.logworkspaceid = logworkspaceid;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "logid", insertable=false, updatable = false)
	public Log getLog() {
		return this.log;
	}

	public void setLog(Log log) {
		this.log = log;
	}
	
	@Column(name = "logid", nullable = false)
	public int getLogid(){
		return this.logid;
	}
	
	public void setLogid(int logid){
		this.logid = logid;
	}
	
	@Column(name = "workspaceid", nullable = false)
	public int getWorkspaceid(){
		return this.workspaceid;
	}
	
	public void setWorkspaceid(int workspaceid){
		this.workspaceid = workspaceid;
	}
	
	public JSONObject toJSONObject(){
		try{
			JSONObject object = new JSONObject();
			object.put("logworkspaceid", this.logworkspaceid);
			object.put("logid", this.logid);
			object.put("workspaceid", this.workspaceid);
			return object;
		}catch(JSONException e){}
		return null;
	}
}
