/**
 * Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity;

// Generated Sep 30, 2011 1:24:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * Messagearchive generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "messagearchive")
@SequenceGenerator(
	name="SEQ_STORE",
	sequenceName="message_archive_seq",
	allocationSize=1
)
public class MessageArchive implements java.io.Serializable {

	private int messagearchiveid;
	private String topic;
	private Date clienttimestamp;
	private Date insertedtimestamp;
	private String user;
	private String messagetype;
	private String message;
	private long seqtime;
	private long seqnum;

	public MessageArchive() {
	}
	
	public MessageArchive(String topic, Date clienttimestamp, 
			Date insertedtimestamp, String user, String messagetype, 
			String message, long seqtime, long seqnum) {
		this.topic = topic;
		this.clienttimestamp = clienttimestamp;
		this.insertedtimestamp = insertedtimestamp;
		this.user = user;
		this.messagetype = messagetype;
		this.message = message;
		this.seqtime = seqtime;
		this.seqnum = seqnum;
	}

	@Id @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_STORE")
	@Column(name = "messagearchiveid", unique = true, nullable = false)
	public int getMessageArchiveId() {
		return this.messagearchiveid;
	}

	public void setMessageArchiveId(int messagearchiveid) {
		this.messagearchiveid = messagearchiveid;
	}

	@Column(name = "topic", nullable = false, length = 96)
	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "clienttimestamp", nullable = false, length = 29)
	public Date getClienttimestamp() {
		return this.clienttimestamp;
	}

	public void setClienttimestamp(Date clienttimestamp) {
		this.clienttimestamp = clienttimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "insertedtimestamp", nullable = false, length = 29)
	public Date getInsertedtimestamp() {
		return this.insertedtimestamp;
	}

	public void setInsertedtimestamp(Date insertedtimestamp) {
		this.insertedtimestamp = insertedtimestamp;
	}

	@Column(name = "`user`", nullable = false, length = 32)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "messagetype", nullable = false, length = 32)
	public String getMessageType() {
		return this.messagetype;
	}

	public void setMessageType(String messagetype) {
		this.messagetype = messagetype;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "seqtime", nullable = false)
	public long getSeqtime() {
		return this.seqtime;
	}

	public void setSeqtime(long seqtime) {
		this.seqtime = seqtime;
	}

	@Column(name = "seqnum", nullable = false)
	public long getSeqnum() {
		return this.seqnum;
	}

	public void setSeqnum(long seqnum) {
		this.seqnum = seqnum;
	}

}
