/**
 * Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity;

// Generated Sep 30, 2011 1:24:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;
import org.json.JSONObject;

/**
 * OrgOrgtype generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "org_orgtype")
public class OrgOrgType extends SADisplayMessageEntity implements SADisplayPersistedEntity {

	private int orgOrgtypeid;
	private Org Org;
	private OrgType Orgtype;
	private int orgid;
	private int orgtypeid;

	public OrgOrgType() {
	}

	public OrgOrgType(int orgOrgtypeid, Org Org) {
		this.orgOrgtypeid = orgOrgtypeid;
		this.Org = Org;
	}

	public OrgOrgType(int orgOrgtypeid, Org Org,
			OrgType Orgtype) {
		this.orgOrgtypeid = orgOrgtypeid;
		this.Org = Org;
		this.Orgtype = Orgtype;
	}

	@Id @GeneratedValue
	@Column(name = "Org_Orgtypeid", unique = true, nullable = false)
	public int getOrgOrgtypeid() {
		return this.orgOrgtypeid;
	}

	public void setOrgOrgtypeid(int orgOrgtypeid) {
		this.orgOrgtypeid = orgOrgtypeid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Orgid", insertable = false, updatable = false)
	public Org getOrg() {
		return this.Org;
	}
	public void setOrg(Org Org) {
		this.Org = Org;
	}

	
	@Column(name = "orgid", nullable = false)
	public int getOrgid() {
		return this.orgid;
	}

	public void setOrgid(int orgid) {
		this.orgid = orgid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Orgtypeid", insertable = false, updatable = false)
	public OrgType getOrgtype() {
		return this.Orgtype;
	}

	public void setOrgtype(OrgType Orgtype) {
		this.Orgtype = Orgtype;
	}
	
	@Column(name = "orgtypeid", nullable = false)
	public int getOrgtypeid() {
		return this.orgtypeid;
	}

	public void setOrgtypeid(int orgtypeid) {
		this.orgtypeid = orgtypeid;
	}
	
	public JSONObject toJSONObject(){
		JSONObject obj = new JSONObject();
		try{
			obj.put("orgorgtypeid", this.orgOrgtypeid);
			obj.put("orgid", this.orgid);
			obj.put("orgtypeid", this.orgtypeid);
		}catch(Exception e){}
		return obj;
		
	}

}
