/**
 * Copyright (c) 2008-2016, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity;

// Generated Sep 30, 2011 1:24:44 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;
import org.json.JSONObject;

/**
 * UserFeature generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "userfeature")
public class UserFeature extends SADisplayMessageEntity implements SADisplayPersistedEntity {

	private Feature feature;
	private User user;
	
	private long userId;
	private long featureId;
	private int userFeatureId;
	private int workspaceId;

	public UserFeature() {
	}

	public UserFeature(int userId, long featureId, int workspaceId) {
		this.userId = userId;
		this.featureId = featureId;
		this.workspaceId = workspaceId;
	}
	
	public int getUserFeatureId() {
        return this.userFeatureId;
    }

    public void setUserFeatureId(int userFeatureId) {
        this.userFeatureId = userFeatureId;
    }

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}
	
	public int getWorkspaceId() {
		return this.workspaceId;
	}

	public void setWorkspaceid(int workspaceId) {
		this.workspaceId = workspaceId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Feature getFeature() {
		return this.feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}
    
    public long getFeatureId() {
        return this.featureId;
    }

    public void setFeatureId(long featureId) {
        this.featureId = featureId;
    }
    
    public JSONObject toJSONObject(){
		JSONObject obj = new JSONObject();
		try{
			obj.put("userfeatureid", this.userFeatureId);
			obj.put("featureid", this.featureId);
			obj.put("userId", this.userId);
		}catch(Exception e){}
		return obj;
	}

}
