/**
 * Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity;

// Generated May 31, 2013 3:56:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import org.json.JSONException;
import org.json.JSONObject;

import edu.mit.ll.nics.common.entity.SADisplayMessageEntity;
import edu.mit.ll.nics.common.entity.SADisplayPersistedEntity;
import edu.mit.ll.nics.common.entity.User;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info", schema = "public")
public class UserInfo extends SADisplayMessageEntity implements SADisplayPersistedEntity {

	private int userId;
	private User user;
	private String rank;
	private String primaryMobilePhone;
	private String primaryHomePhone;
	private String primaryEmailAddr;
	private String homeBaseName;
	private String homeBaseStreet;
	private String homeBaseCity;
	private String homeBaseState;
	private String homeBaseZip;
	private String agency;
	private Integer approxWeight;
	private String remarks;
	private long creationDateTime;	
	

	public UserInfo() {
		this.approxWeight = 0;
	}

	public UserInfo(User user, long creationDateTime) {
		this();
		
		this.user = user;
		this.creationDateTime = creationDateTime;
	}

	public UserInfo(User user, String rank, String primaryMobilePhone,
			String primaryHomePhone, String primaryEmailAddr,
			String homeBaseName, String homeBaseStreet, String homeBaseCity,
			String homeBaseState, String homeBaseZip, String agency,
			Integer approxWeight, String remarks, long creationDateTime) {
		this.user = user;
		this.rank = rank;
		this.primaryMobilePhone = primaryMobilePhone;
		this.primaryHomePhone = primaryHomePhone;
		this.primaryEmailAddr = primaryEmailAddr;
		this.homeBaseName = homeBaseName;
		this.homeBaseStreet = homeBaseStreet;
		this.homeBaseCity = homeBaseCity;
		this.homeBaseState = homeBaseState;
		this.homeBaseZip = homeBaseZip;
		this.agency = agency;
		this.approxWeight = approxWeight;
		this.remarks = remarks;
		this.creationDateTime = creationDateTime;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "user"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "rank", length = 50)
	public String getRank() {
		return this.rank;
	}

	public void setRank(String rank) {
		this.rank = rank;
	}

	@Column(name = "primary_mobile_phone", length = 15)
	public String getPrimaryMobilePhone() {
		return this.primaryMobilePhone;
	}

	public void setPrimaryMobilePhone(String primaryMobilePhone) {
		this.primaryMobilePhone = primaryMobilePhone;
	}

	@Column(name = "primary_home_phone", length = 15)
	public String getPrimaryHomePhone() {
		return this.primaryHomePhone;
	}

	public void setPrimaryHomePhone(String primaryHomePhone) {
		this.primaryHomePhone = primaryHomePhone;
	}

	@Column(name = "primary_email_addr", length = 320)
	public String getPrimaryEmailAddr() {
		return this.primaryEmailAddr;
	}

	public void setPrimaryEmailAddr(String primaryEmailAddr) {
		this.primaryEmailAddr = primaryEmailAddr;
	}

	@Column(name = "home_base_name", length = 30)
	public String getHomeBaseName() {
		return this.homeBaseName;
	}

	public void setHomeBaseName(String homeBaseName) {
		this.homeBaseName = homeBaseName;
	}

	@Column(name = "home_base_street", length = 30)
	public String getHomeBaseStreet() {
		return this.homeBaseStreet;
	}

	public void setHomeBaseStreet(String homeBaseStreet) {
		this.homeBaseStreet = homeBaseStreet;
	}

	@Column(name = "home_base_city", length = 25)
	public String getHomeBaseCity() {
		return this.homeBaseCity;
	}

	public void setHomeBaseCity(String homeBaseCity) {
		this.homeBaseCity = homeBaseCity;
	}

	@Column(name = "home_base_state", length = 15)
	public String getHomeBaseState() {
		return this.homeBaseState;
	}

	public void setHomeBaseState(String homeBaseState) {
		this.homeBaseState = homeBaseState;
	}

	@Column(name = "home_base_zip", length = 10)
	public String getHomeBaseZip() {
		return this.homeBaseZip;
	}

	public void setHomeBaseZip(String homeBaseZip) {
		this.homeBaseZip = homeBaseZip;
	}

	@Column(name = "agency", length = 30)
	public String getAgency() {
		return this.agency;
	}

	public void setAgency(String agency) {
		this.agency = agency;
	}

	@Column(name = "approx_weight")
	public Integer getApproxWeight() {
		return this.approxWeight;
	}

	public void setApproxWeight(Integer approxWeight) {
		this.approxWeight = approxWeight;
	}

	@Column(name = "remarks", length = 60)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "creation_date_time", nullable = false)
	public long getCreationDateTime() {
		return this.creationDateTime;
	}

	public void setCreationDateTime(long creationDateTime) {
		this.creationDateTime = creationDateTime;
	}

	
	@Override
	public JSONObject toJSONObject() throws JSONException {
		JSONObject object = new JSONObject();
		
		object.put("userId", this.userId);
		object.put("rank", this.rank);
		object.put("primaryMobilePhone", this.primaryMobilePhone);
		object.put("primaryHomePhoine", this.primaryHomePhone);
		object.put("primaryEmailAddr", this.primaryEmailAddr);
		object.put("homeBaseName", this.homeBaseName);
		object.put("homeBaseStreet", this.homeBaseStreet);
		object.put("homeBaseCity", this.homeBaseCity);
		object.put("homeBaseState", this.homeBaseState);
		object.put("homeBaseZip", this.homeBaseZip);
		object.put("agency", this.agency);
		object.put("approxWeight", this.approxWeight);
		object.put("remarks", this.remarks);
		object.put("creationDateTime", this.creationDateTime);
		
		return object;
	}

}
