/**
 * Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity.datalayer;

// Generated Nov 30, 2011 2:53:26 PM by Hibernate Tools 3.4.0.CR1
import edu.mit.ll.nics.common.entity.SADisplayMessageEntity;
import edu.mit.ll.nics.common.entity.SADisplayPersistedEntity;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Datasourcetype generated by hbm2java
 */
@Entity
@Table(name = "datasourcetype", schema = "public")
public class Datasourcetype extends SADisplayMessageEntity implements SADisplayPersistedEntity {

    private Integer datasourcetypeid;
    private String typename;
    private Set<Datasource> datasources = new HashSet<Datasource>(0);

    public Datasourcetype() {
    }

    public Datasourcetype(Integer datasourcetypeid, String typename) {
        this.datasourcetypeid = datasourcetypeid;
        this.typename = typename;
    }

    public Datasourcetype(Integer datasourcetypeid, String typename,
            Set<Datasource> datasources) {
        this.datasourcetypeid = datasourcetypeid;
        this.typename = typename;
        this.datasources = datasources;
    }

    @Id
    @Column(name = "datasourcetypeid", unique = true, nullable = false)
    public Integer getDatasourcetypeid() {
        return this.datasourcetypeid;
    }

    public void setDatasourcetypeid(Integer datasourcetypeid) {
        this.datasourcetypeid = datasourcetypeid;
    }

    @Column(name = "typename", nullable = false, length = 64)
    public String getTypename() {
        return this.typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "datasourcetype")
    public Set<Datasource> getDatasources() {
        return this.datasources;
    }

    public void setDatasources(Set<Datasource> datasources) {
        this.datasources = datasources;
    }

    @Override
    public JSONObject toJSONObject() throws JSONException {
        JSONObject json = new JSONObject();
        json.put("datasourcetypeid", this.datasourcetypeid);
        json.put("typename", this.typename);
        return json;
    }
}
