/**
 * Copyright (c) 2008-2015, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity.datalayer;

// Generated Nov 30, 2011 2:53:26 PM by Hibernate Tools 3.4.0.CR1
import edu.mit.ll.nics.common.entity.SADisplayMessageEntity;
import edu.mit.ll.nics.common.entity.SADisplayPersistedEntity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import edu.mit.ll.nics.common.entity.Usersession;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Datalayersource generated by hbm2java
 */
@Entity
@Table(name = "datalayersource", schema = "public")
public class Datalayersource extends SADisplayMessageEntity implements SADisplayPersistedEntity {

    private String datalayersourceid;
    private Datasource datasource;
    private String datasourceid;
    private int refreshrate;
    private String stylepath;
    private String imageformat;
    private String nativeprojection;
    private String layername;
    private String tilegridset;
    private String attributes;
    private Integer tilesize;
    private Double opacity;
    private Date created;
    private Usersession usersession;
    private int usersessionid;

    public Datalayersource() {
    }

    public Datalayersource(String datalayersourceid,
           Datasource datasource, int refreshrate, Date created) {
        this.datalayersourceid = datalayersourceid;
        this.datasource = datasource;
        this.refreshrate = refreshrate;
        this.created = created;
    }

    public Datalayersource(String datalayersourceid,
            Datasource datasource, int refreshrate, String stylepath,
            String imageformat, String nativeprojection, String layername,
            String tilegridset, Integer tilesize, Date created, Double opacity) {
        this.datalayersourceid = datalayersourceid;
        this.datasource = datasource;
        this.refreshrate = refreshrate;
        this.stylepath = stylepath;
        this.imageformat = imageformat;
        this.nativeprojection = nativeprojection;
        this.layername = layername;
        this.tilegridset = tilegridset;
        this.tilesize = tilesize;
        this.created = created;
        this.opacity = opacity;
    }

    @Id
    @Column(name = "datalayersourceid", unique = true, nullable = false)
    public String getDatalayersourceid() {
        return this.datalayersourceid;
    }

    public void setDatalayersourceid(String datalayersourceid) {
        this.datalayersourceid = datalayersourceid;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "datasourceid", insertable = false, updatable = false)
    public Datasource getDatasource() {
        return this.datasource;
    }

    public void setDatasource(Datasource datasource) {
        this.datasource = datasource;
    }

    @Column(name = "refreshrate", nullable = false)
    public int getRefreshrate() {
        return this.refreshrate;
    }

    public void setRefreshrate(int refreshrate) {
        this.refreshrate = refreshrate;
    }

    @Column(name = "stylepath", length = 128)
    public String getStylepath() {
        return this.stylepath;
    }

    public void setStylepath(String stylepath) {
        this.stylepath = stylepath;
    }

    @Column(name = "imageformat", length = 64)
    public String getImageformat() {
        return this.imageformat;
    }

    public void setImageformat(String imageformat) {
        this.imageformat = imageformat;
    }

    @Column(name = "nativeprojection", length = 64)
    public String getNativeprojection() {
        return this.nativeprojection;
    }

    public void setNativeprojection(String nativeprojection) {
        this.nativeprojection = nativeprojection;
    }

    @Column(name = "layername", length = 64)
    public String getLayername() {
        return this.layername;
    }

    public void setLayername(String layername) {
        this.layername = layername;
    }

    @Column(name = "tilegridset", length = 64)
    public String getTilegridset() {
        return this.tilegridset;
    }

    public void setTilegridset(String tilegridset) {
        this.tilegridset = tilegridset;
    }

    @Column(name = "tilesize")
    public Integer getTilesize() {
        return this.tilesize;
    }

    public void setTilesize(Integer tilesize) {
        this.tilesize = tilesize;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 29)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "datasourceid", nullable = false)
    public String getDatasourceid() {
        return datasourceid;
    }

    public void setDatasourceid(String datasourceid) {
        this.datasourceid = datasourceid;
    }

      @Column(name = "opacity", precision = 17, scale = 17)
	public Double getOpacity() {
		return this.opacity;
	}

	public void setOpacity(Double opacity) {
		this.opacity = opacity;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usersessionid", insertable=false, updatable = false)
	public Usersession getUsersession() {
		return this.usersession;
	}

	public void setUsersession(Usersession usersession) {
		this.usersession = usersession;
	}
	
	@Column(name = "usersessionid", nullable = false)
	public int getUsersessionid(){
		return this.usersessionid;
	}
	
	public void setUsersessionid(int usersessionid){
		this.usersessionid = usersessionid;
	}
	
	@Column(name = "attributes")
	public String getAttributes(){
		return this.attributes;
	}
	
	public void setAttributes(String attributes){
		this.attributes = attributes;
	}

    @Override
    public JSONObject toJSONObject() {
        JSONObject json = new JSONObject();
        try {
            json.put("datalayersourceid", this.datalayersourceid);
            json.put("created", this.created);
            json.put("imageformat", this.imageformat);
            json.put("layername", this.layername);
            json.put("nativeprojection", this.nativeprojection);
            json.put("refreshrate", this.refreshrate);
            json.put("stylepath", this.stylepath);
            json.put("tilegridset", this.tilegridset);
            json.put("tilesize", this.tilesize);
            json.put("datasourceid", this.datasourceid);
            json.put("opacity", opacity);
            json.put("usersessionid", this.usersessionid);
            json.put("attributes", this.attributes);
        } catch (JSONException ex) {
            Logger.getLogger(Document.class.getName()).log(Level.SEVERE, null, ex);
        }
        return json;
    }
}
