/**
 * Copyright (c) 2008-2016, Massachusetts Institute of Technology (MIT)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its contributors
 * may be used to endorse or promote products derived from this software without
 * specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package edu.mit.ll.nics.common.entity.datalayer;

// Generated Nov 30, 2011 2:53:26 PM by Hibernate Tools 3.4.0.CR1
import edu.mit.ll.nics.common.entity.SADisplayMessageEntity;
import edu.mit.ll.nics.common.entity.SADisplayPersistedEntity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.json.JSONException;
import org.json.JSONObject;

/**
 * Folder generated by hbm2java
 */
@Entity
@Table(name = "rootfolder", schema = "public")
public class Rootfolder extends SADisplayMessageEntity implements SADisplayPersistedEntity {

    private String rootid;
    private String tabname;
    private String folderid;
    private Folder folder;
    private int workspaceid;

    public Rootfolder() {
    }

    public Rootfolder(String rootid, String tabname, String folderid, int workspaceid) {
        this.rootid = rootid;
        this.tabname = tabname;
        this.folderid = folderid;
        this.workspaceid = workspaceid;
    }

    public Rootfolder(String rootid, String tabname, String folderid,
            Folder folder, int workspaceid) {
        this.rootid = rootid;
        this.tabname = tabname;
        this.folderid = folderid;
        this.folder = folder;
        this.workspaceid = workspaceid;
    }

    @Id
    @Column(name = "rootid", unique = true, nullable = false)
    public String getRootid() {
        return this.rootid;
    }

    public void setRootid(String rootid) {
        this.rootid = rootid;
    }

    @Column(name = "tabname", nullable = false, length = 256)
    public String getTabname() {
        return this.tabname;
    }

    public void setTabname(String tabname) {
        this.tabname = tabname;
    }

    @Column(name = "folderid")
    public String getFolderid() {
        return this.folderid;
    }

    public void setFolderid(String folderid) {
        this.folderid = folderid;
    }
    
    @Column(name = "workspaceid")
    public int getWorkspaceid() {
        return this.workspaceid;
    }

    public void setWorkspaceid(int workspaceid) {
        this.workspaceid = workspaceid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "folderid", insertable = false, updatable = false)
    public Folder getFolder() {
        return this.folder;
    }

    public void setFolder(Folder folder) {
        this.folder = folder;
    }

    @Override
    public JSONObject toJSONObject() throws JSONException {
        JSONObject json = new JSONObject();
        json.put("rootid", this.rootid);
        json.put("tabname", this.tabname);
        json.put("folderid", this.folderid);
        json.put("workspaceid", this.workspaceid);
        return json;
    }
}